### PR TITLE
Log "deleting local zip" as info rather than error

### LINKED ISSUE #59: Error log noise: "Deleting local database zip file"
We're logging errors to an aggregator, and we are getting a lot of noise with `Deleting local database zip file:/...` messages.

It appears to come from vendor/weareferal/remote-core/src/services/ProviderService.php line 129.

I haven't dug deep by any means, but on the surface it looks like it's checking whether we wanted to keep the local file or not, and if not, deleting it. This seems like totally expected behaviour so I'm not sure why it would be logged as an error. Perhaps a mistake?

### PR DESCRIPTION
**Pull request by tremby**
Fixes https://github.com/timmyomahony/craft-remote-backup/issues/59

### CODE REVIEW

**Comment by timmyomahony** [comment]
This is merged in the latest `5.0.0` released for `remote-backup` and `remote-core`. Thanks for the help.

**Comment by tremby** [comment]
Hi @timmyomahony. Thanks for rolling this in to the new versions. However, we have a large project being held at Craft 4 which we'd really like this fix for. Any chance of it being included in the 4.x branch too, please?

**Comment by timmyomahony** [comment]
Hi @tremby no problem, I've pushed a new version for `remote-sync` (`4.1.5`) and `remote-backup` (`4.1.7`) that should include this fix.

**Comment by tremby** [comment]
Thank you!

**Pull request closed without merging**
